# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\env_tt\cv_plus.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(250, 305)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 231, 91))
        self.groupBox.setObjectName("groupBox")
        self.btn_mouse_open = QtWidgets.QPushButton(self.groupBox)
        self.btn_mouse_open.setGeometry(QtCore.QRect(10, 20, 211, 31))
        self.btn_mouse_open.setObjectName("btn_mouse_open")
        self.label_mouse = QtWidgets.QLabel(self.groupBox)
        self.label_mouse.setGeometry(QtCore.QRect(10, 50, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.label_mouse.setFont(font)
        self.label_mouse.setObjectName("label_mouse")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 110, 231, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.btn_mouse_macro = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_mouse_macro.setGeometry(QtCore.QRect(10, 20, 211, 31))
        self.btn_mouse_macro.setObjectName("btn_mouse_macro")
        self.label_mouse_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_mouse_2.setGeometry(QtCore.QRect(149, 55, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.label_mouse_2.setFont(font)
        self.label_mouse_2.setObjectName("label_mouse_2")
        self.lineEdit_auto = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_auto.setGeometry(QtCore.QRect(180, 60, 41, 20))
        self.lineEdit_auto.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_auto.setObjectName("lineEdit_auto")
        self.label_mouse_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_mouse_3.setGeometry(QtCore.QRect(13, 54, 16, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.label_mouse_3.setFont(font)
        self.label_mouse_3.setObjectName("label_mouse_3")
        self.lineEdit_X = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_X.setGeometry(QtCore.QRect(30, 60, 41, 20))
        self.lineEdit_X.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_X.setObjectName("lineEdit_X")
        self.lineEdit_Y = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_Y.setGeometry(QtCore.QRect(100, 60, 41, 20))
        self.lineEdit_Y.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Y.setObjectName("lineEdit_Y")
        self.label_mouse_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_mouse_4.setGeometry(QtCore.QRect(83, 54, 16, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.label_mouse_4.setFont(font)
        self.label_mouse_4.setObjectName("label_mouse_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 220, 231, 80))
        self.groupBox_3.setObjectName("groupBox_3")
        self.btn_mouse_click = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_mouse_click.setGeometry(QtCore.QRect(10, 20, 211, 31))
        self.btn_mouse_click.setObjectName("btn_mouse_click")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_3)
        self.progressBar.setGeometry(QtCore.QRect(12, 51, 211, 23))
        self.progressBar.setMaximum(1000)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.btn_mouse_open.clicked.connect(MainWindow.mouse_open)
        self.btn_mouse_macro.clicked.connect(MainWindow.mouse_marco)
        self.btn_mouse_click.clicked.connect(MainWindow.mouse_click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "滑鼠位置偵測"))
        self.btn_mouse_open.setText(_translate("MainWindow", "Run"))
        self.label_mouse.setText(_translate("MainWindow", "Point"))
        self.groupBox_2.setTitle(_translate("MainWindow", "滑鼠巨集"))
        self.btn_mouse_macro.setText(_translate("MainWindow", "Run"))
        self.label_mouse_2.setText(_translate("MainWindow", "連點"))
        self.lineEdit_auto.setText(_translate("MainWindow", "1"))
        self.label_mouse_3.setText(_translate("MainWindow", "X"))
        self.lineEdit_X.setText(_translate("MainWindow", "0"))
        self.lineEdit_Y.setText(_translate("MainWindow", "0"))
        self.label_mouse_4.setText(_translate("MainWindow", "Y"))
        self.groupBox_3.setTitle(_translate("MainWindow", "點擊測試"))
        self.btn_mouse_click.setText(_translate("MainWindow", "Click"))
        self.progressBar.setFormat(_translate("MainWindow", "%v"))

